In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [2]:
df = pd.read_csv('./data/Iris.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/Iris.csv'

In [3]:
df['SepalWidthCm'].to_frame().head()

NameError: name 'df' is not defined

In [4]:
part = 'Sepal'

df[f'{part}WidthCm'].to_frame().head()

NameError: name 'df' is not defined

In [5]:
df[['PetalWidthCm', 'PetalLengthCm']].head()

NameError: name 'df' is not defined

In [6]:
part = 'Petal'

df[[f'{part}WidthCm', f'{part}LengthCm']].head()

NameError: name 'df' is not defined

In [7]:
import pandas as pd

print(pd.__version__)

2.3.3

In [8]:
d = {'penjual':['bejo', 'tejo', 'wati', 'bejo', 'cecep', 'tejo', 'wati', 'bejo'], 
     'barang':['monitor', 'monitor', 'keyboard', 'mouse', 'keyboard', 'monitor', 'laptop', 'monitor']}

df = pd.DataFrame(d)
df

  penjual    barang
0    bejo   monitor
1    tejo   monitor
2    wati  keyboard
3    bejo     mouse
4   cecep  keyboard
5    tejo   monitor
6    wati    laptop
7    bejo   monitor

In [9]:
cols = ['penjual', 'barang']

for col in cols:
    df[f'count_tiap_{col}'] =  df.groupby(col).cumcount() + 1
    
df

  penjual    barang  count_tiap_penjual  count_tiap_barang
0    bejo   monitor                   1                  1
1    tejo   monitor                   1                  2
2    wati  keyboard                   1                  1
3    bejo     mouse                   2                  1
4   cecep  keyboard                   1                  2
5    tejo   monitor                   2                  3
6    wati    laptop                   2                  1
7    bejo   monitor                   3                  4

In [10]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [11]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  7  5  1  7  4
1  2  6  3  2  4
2  7  5  7  2  8
3  1  3  2  5  3
4  5  9  7  1  4
5  6  3  8  4  6
6  8  4  2  6  8
7  7  1  4  5  1
8  3  3  9  1  4
9  9  4  2  5  8

In [12]:
df[df['A'].between(2, 5)]

   A  B  C  D  E
1  2  6  3  2  4
4  5  9  7  1  4
8  3  3  9  1  4

In [13]:
df[df['A'].between(2, 5, inclusive='left')]

   A  B  C  D  E
1  2  6  3  2  4
8  3  3  9  1  4

In [14]:
df[df['A'].between(2, 5, inclusive='right')]

   A  B  C  D  E
4  5  9  7  1  4
8  3  3  9  1  4

In [15]:
df[df['A'].between(2, 5, inclusive='both')]

   A  B  C  D  E
1  2  6  3  2  4
4  5  9  7  1  4
8  3  3  9  1  4

In [16]:
df[df['A'].between(2, 5, inclusive='neither')]

   A  B  C  D  E
8  3  3  9  1  4

In [17]:
import pandas as pd

print(pd.__version__)

2.3.3

In [18]:
d = {
'kode_area': [123, 456, 789, 321],
'pabrik': [4, 2, 5, 0],
'gudang': [2, 4, 7, 3],
'toko': [64, 32, 15, 24]
}

df = pd.DataFrame(d)
df

   kode_area  pabrik  gudang  toko
0        123       4       2    64
1        456       2       4    32
2        789       5       7    15
3        321       0       3    24

In [19]:
df = df.melt(id_vars='kode_area', 
             var_name='jenis_bangunan', 
             value_name='jumlah')
df

    kode_area jenis_bangunan  jumlah
0         123         pabrik       4
1         456         pabrik       2
2         789         pabrik       5
3         321         pabrik       0
4         123         gudang       2
5         456         gudang       4
6         789         gudang       7
7         321         gudang       3
8         123           toko      64
9         456           toko      32
10        789           toko      15
11        321           toko      24