In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  6  3  3  1  7
1  8  1  9  5  9
2  7  2  3  1  2
3  1  6  2  5  5
4  9  9  9  9  2

In [3]:
df.loc[:, ::-1]

   E  D  C  B  A
0  7  1  3  3  6
1  9  5  9  1  8
2  2  1  3  2  7
3  5  5  2  6  1
4  2  9  9  9  9

In [4]:
df.loc[::-1]

   A  B  C  D  E
4  9  9  9  9  2
3  1  6  2  5  5
2  7  2  3  1  2
1  8  1  9  5  9
0  6  3  3  1  7

In [5]:
df.loc[::-1].reset_index(drop=True)

   A  B  C  D  E
0  9  9  9  9  2
1  1  6  2  5  5
2  7  2  3  1  2
3  8  1  9  5  9
4  6  3  3  1  7

In [6]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [7]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  5  3  8  8  1
1  7  4  8  7  2
2  2  9  3  5  1
3  4  7  8  9  4
4  4  1  1  2  9

In [8]:
df.rename(columns={'C':'Hobi'})

   A  B  Hobi  D  E
0  5  3     8  8  1
1  7  4     8  7  2
2  2  9     3  5  1
3  4  7     8  9  4
4  4  1     1  2  9

In [9]:
df.rename(columns={'A':'Nama', 'B':'Alamat', 'D':'Kota'})

   Nama  Alamat  C  Kota  E
0     5       3  8     8  1
1     7       4  8     7  2
2     2       9  3     5  1
3     4       7  8     9  4
4     4       1  1     2  9

In [10]:
import pandas as pd

print(pd.__version__)

2.3.3

In [11]:
n_rows = 30
n_cols = 4
cols = ['A', 'B', 'C', 'D']

df = pd.DataFrame(np.random.randn(n_rows, n_cols), columns=cols)

nan_mask = np.random.rand(n_rows, n_cols) < 0.2
df[nan_mask] = np.nan

df = df.reset_index()
df.head()

   index         A         B         C         D
0      0  0.463197 -0.014126 -1.253583 -0.625694
1      1 -1.064294 -1.312001       NaN       NaN
2      2  0.755962  0.638435  0.091473  1.373740
3      3  0.412721 -0.288418  0.840935  1.244033
4      4       NaN  0.200468 -2.255023       NaN

In [12]:
df = df.rename(columns={'index':'Z'})
df.head()

   Z         A         B         C         D
0  0  0.463197 -0.014126 -1.253583 -0.625694
1  1 -1.064294 -1.312001       NaN       NaN
2  2  0.755962  0.638435  0.091473  1.373740
3  3  0.412721 -0.288418  0.840935  1.244033
4  4       NaN  0.200468 -2.255023       NaN

In [13]:
df_backup = df.copy(deep=True)

In [14]:
df = df.dropna(axis='columns') 
df.head()

   Z
0  0
1  1
2  2
3  3
4  4

In [15]:
df = df_backup.copy(deep=True)
df = df.dropna(axis='rows')
df.head()

   Z         A         B         C         D
0  0  0.463197 -0.014126 -1.253583 -0.625694
2  2  0.755962  0.638435  0.091473  1.373740
3  3  0.412721 -0.288418  0.840935  1.244033
5  5  0.909498 -0.056087 -0.384254 -0.457146
6  6 -1.357455 -0.464572 -0.939150  0.853504

In [16]:
df = df_backup.copy(deep=True)
df.isna().mean()

Z    0.000000
A    0.166667
B    0.333333
C    0.233333
D    0.233333
dtype: float64

In [17]:
treshold = len(df) * 0.9
df = df.dropna(thresh=treshold, axis='columns')
df.head()

   Z
0  0
1  1
2  2
3  3
4  4

In [18]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [19]:
data = {'A':[15, 15, 18, np.nan, 12], 
        'B':[15, 15, 18, np.nan, 12]}

df = pd.DataFrame(data)
df

      A     B
0  15.0  15.0
1  15.0  15.0
2  18.0  18.0
3   NaN   NaN
4  12.0  12.0

In [20]:
df['A']

0    15.0
1    15.0
2    18.0
3     NaN
4    12.0
Name: A, dtype: float64

In [21]:
type(df['A'])

pandas.core.series.Series

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df['A'] == df['B']

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [24]:
df['A'].equals(df['B'])

True

In [25]:
df1 = df.copy(deep=True)

df.equals(df1)

True

In [26]:
df == df1

       A      B
0   True   True
1   True   True
2   True   True
3  False  False
4   True   True