In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [2]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0   6   9  17  14   7
1   2  11   7   7  15
2   7  12   8   4   8
3   2   9   9  14  10
4   9   3   9   6   4
5  19   2  11  14   5
6   4  13  19  10  17
7   5   9  10  17  12
8   1   8  14   9  13
9  15  15  15  16  17

In [3]:
df.shape

(10, 5)

In [4]:
proporsi = 0.7
df_1 = df.sample(frac=proporsi)
df_2 = df.drop(df_1.index)

print(f'df_1 shape: {df_1.shape}')
print(f'df_2 shape: {df_2.shape}')

df_1 shape: (7, 5)
df_2 shape: (3, 5)

In [5]:
df_1

    A   B   C   D   E
5  19   2  11  14   5
3   2   9   9  14  10
8   1   8  14   9  13
2   7  12   8   4   8
9  15  15  15  16  17
1   2  11   7   7  15
6   4  13  19  10  17

In [6]:
df_2

   A  B   C   D   E
0  6  9  17  14   7
4  9  3   9   6   4
7  5  9  10  17  12

In [7]:
import pandas as pd

print(pd.__version__)

2.3.3

In [12]:
import os
print("Current directory:")
print(os.getcwd())

print("\nIsi folder sekarang:")
print(os.listdir())

Current directory:
c:\Pandas

Isi folder sekarang:
['.git', '01.pandasweek01.ipynb', '01.pandasweek02.ipynb', '01.pandasweek03.ipynb']

In [13]:
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.head()

   a   b   c   d   e
0  6   9  17  14   7
1  2  11   7   7  15
2  7  12   8   4   8
3  2   9   9  14  10
4  9   3   9   6   4

In [2]:
import pandas as pd
import os

csv_path = input("Masukkan path lengkap file titanicfull.csv: ").strip()

if not os.path.isfile(csv_path):
    raise FileNotFoundError("File tidak ditemukan. Path salah.")

df = pd.read_csv(csv_path)

df_backup = df.copy(deep=True)

df.columns = (
    df.columns
      .astype(str)
      .str.lower()
      .str.strip()
      .str.replace(' ', '_')
)

df.head()

FileNotFoundError: File tidak ditemukan. Path salah.

In [3]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [4]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0   2  10  19   8   8
1  12   6   7  19  15
2  11   7  16  17   8
3  16  14   7  16  10
4  11   8   5  17  14
5   6  11  17  16   9
6  15  11   8   5  18
7   7  12   8   6  18
8  18  17   4  15  19
9  14  16  10   4   1

In [5]:
df.loc[[0,3,4], ['B','E']]

    B   E
0  10   8
3  14  10
4   8  14

In [6]:
df.loc[df['B']>10, ['B','D','E']]

    B   D   E
3  14  16  10
5  11  16   9
6  11   5  18
7  12   6  18
8  17  15  19
9  16   4   1

In [7]:
df.loc[0:4, 'B':'D']

    B   C   D
0  10  19   8
1   6   7  19
2   7  16  17
3  14   7  16
4   8   5  17

In [8]:
import pandas as pd

print(pd.__version__)

2.3.3

In [9]:
data = {'day':[1, 2, 10 ,25, 12], 
        'month':[1, 2, 4, 5, 6], 
        'year':[2000, 2001, 2010, 2015, 2020]}

df = pd.DataFrame(data)
df

   day  month  year
0    1      1  2000
1    2      2  2001
2   10      4  2010
3   25      5  2015
4   12      6  2020

In [10]:
df['penaggalan'] = pd.to_datetime(df[['day', 'month', 'year']])
df

   day  month  year penaggalan
0    1      1  2000 2000-01-01
1    2      2  2001 2001-02-02
2   10      4  2010 2010-04-10
3   25      5  2015 2015-05-25
4   12      6  2020 2020-06-12

In [11]:
df.dtypes

day                    int64
month                  int64
year                   int64
penaggalan    datetime64[ns]
dtype: object