In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [24]:
from sklearn.datasets import load_iris

In [25]:
df.groupby('Species')['PetalLengthCm'].count().to_frame()

KeyError: 'Species'

In [4]:
df.groupby('Species')['PetalLengthCm'].mean().to_frame()

NameError: name 'df' is not defined

In [23]:

from dataclasses import _DataclassFactory


_DataclassFactory.groupby('Species')['PetalLengthCm'].median().to_frame()

ImportError: cannot import name '_DataclassFactory' from 'dataclasses' (c:\Program Files\Python314\Lib\dataclasses.py)

In [6]:
df.groupby('Species')['PetalLengthCm'].agg(['count', 'mean', 'median'])

NameError: name 'df' is not defined

In [7]:
df.groupby('Species')['PetalLengthCm'].describe()

NameError: name 'df' is not defined

In [8]:
import pandas as pd

print(pd.__version__)

2.3.3

In [9]:
df_titanic = pd.read_csv('./data/titanicfull.csv')
df_titanic.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/titanicfull.csv'

In [10]:
df_iris = pd.read_csv('./data/Iris.csv')
df_iris.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/Iris.csv'

In [11]:
df_titanic.info(memory_usage='deep')

NameError: name 'df_titanic' is not defined

In [12]:
df_iris.info(memory_usage='deep')

df_titanic.memory_usage(deep=True)

NameError: name 'df_iris' is not defined

In [13]:

df_iris.memory_usage(deep=True)

NameError: name 'df_iris' is not defined

In [14]:
import pandas as pd

print(pd.__version__)

2.3.3

In [15]:
d = {'kolom_satu':[1, 2, 3, 4, 5], 
     'kolom dua':[10, 20, 30, 40, 50]}
df = pd.DataFrame(d)
df

   kolom_satu  kolom dua
0           1         10
1           2         20
2           3         30
3           4         40
4           5         50

In [16]:
df.query('kolom_satu > 2')

   kolom_satu  kolom dua
2           3         30
3           4         40
4           5         50

In [17]:

df.query('`kolom dua` > 30')

   kolom_satu  kolom dua
3           4         40
4           5         50

In [18]:
import pandas as pd

print(pd.__version__)

2.3.3

In [19]:
s = pd.Series(range(1591683521, 1592201921, 3600))
s = pd.to_datetime(s, unit='s')
s.head()

0   2020-06-09 06:18:41
1   2020-06-09 07:18:41
2   2020-06-09 08:18:41
3   2020-06-09 09:18:41
4   2020-06-09 10:18:41
dtype: datetime64[ns]

In [20]:
s = s.dt.tz_localize('UTC')
s.head()

0   2020-06-09 06:18:41+00:00
1   2020-06-09 07:18:41+00:00
2   2020-06-09 08:18:41+00:00
3   2020-06-09 09:18:41+00:00
4   2020-06-09 10:18:41+00:00
dtype: datetime64[ns, UTC]

In [21]:
s = s.dt.tz_convert('Asia/Jakarta')
s.head()

0   2020-06-09 13:18:41+07:00
1   2020-06-09 14:18:41+07:00
2   2020-06-09 15:18:41+07:00
3   2020-06-09 16:18:41+07:00
4   2020-06-09 17:18:41+07:00
dtype: datetime64[ns, Asia/Jakarta]

In [22]:
s = s.dt.tz_convert('Australia/Hobart')
s.head()

0   2020-06-09 16:18:41+10:00
1   2020-06-09 17:18:41+10:00
2   2020-06-09 18:18:41+10:00
3   2020-06-09 19:18:41+10:00
4   2020-06-09 20:18:41+10:00
dtype: datetime64[ns, Australia/Hobart]