In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

In [3]:
df = pd.read_csv('./data/titanicfull.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/titanicfull.csv'

In [6]:
import pandas as pd

df = pd.read_csv('PATH_CSV_YANG_BENAR')

FileNotFoundError: [Errno 2] No such file or directory: 'PATH_CSV_YANG_BENAR'

In [7]:
df[
    (df['sex']=='female') & 
    (df['age']>=60) & 
    (df['embarked']=='S') & 
    (df['survived']==1)
]

NameError: name 'df' is not defined

In [8]:
kr1 = df['sex']=='female'
kr2 = df['age']>=60
kr3 = df['embarked']=='S'
kr4 = df['survived']==1

df[kr1 & kr2 & kr3 & kr4]

NameError: name 'df' is not defined

In [9]:
import pandas as pd

print(pd.__version__)

2.3.3

In [10]:
df = pd.read_csv('./data/iris_error.csv')
df.head(8)

FileNotFoundError: [Errno 2] No such file or directory: './data/iris_error.csv'

In [11]:
df = pd.read_csv('./data/iris_error.csv', header=2, skiprows=[5,6])
df.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/iris_error.csv'

In [12]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.4.1

In [13]:
n_rows = 6
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  2  3  2  3  3
1  2  3  3  2  2
2  1  4  3  4  1
3  1  4  1  3  2
4  3  2  4  2  2
5  2  2  1  2  3

In [14]:
df.sample(frac=1.0, random_state=1)

   A  B  C  D  E
2  1  4  3  4  1
1  2  3  3  2  2
4  3  2  4  2  2
0  2  3  2  3  3
3  1  4  1  3  2
5  2  2  1  2  3

In [15]:
df.sample(frac=1.0, random_state=1).reset_index(drop=True)

   A  B  C  D  E
0  1  4  3  4  1
1  2  3  3  2  2
2  3  2  4  2  2
3  2  3  2  3  3
4  1  4  1  3  2
5  2  2  1  2  3

In [16]:
import pandas as pd

print(pd.__version__)

2.3.3

In [17]:
df = pd.read_csv('./data/titanicfull.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: './data/titanicfull.csv'

In [18]:
grouped_df = df.groupby('sex')

KeyError: 'sex'

In [19]:
grouped_df.get_group('female').head(10)

NameError: name 'grouped_df' is not defined

In [20]:
grouped_df = df.groupby('survived')

KeyError: 'survived'

In [21]:
grouped_df.get_group(1).head(10)

NameError: name 'grouped_df' is not defined